### ISSUE TITLE
Volume generation

### ISSUE THREAD

**Issue by eliyash** [caiyuanhao1998/X-Gaussian#3]
Hi, 
Regarding volume generation, as I understand, you use classical reconstruction algorithm with noval views, my question is why cant you use the gaussians themselves? As they are 3d objects with size?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests
Because Gaussian Splatting cannot directly infer the radiodensity of 3D points.
It is not an easy thing. The attribute "opacity" is not density. We have tried various volume density blending strategies to blend the density by using opacity. But it is very slow and the accuracy is pretty poor.
