### ISSUE TITLE
Questions about CT Reconstruction

### ISSUE THREAD

**Issue by byungjur96** [caiyuanhao1998/X-Gaussian#4]
Hi, first of all, thank you for sharing your fascinating research.
I'm experiencing amazing result with your method with CT reconstruction tasks.
However, I'm currently stuck in saving the result 3D CT volume.
Can you help me how to save the result 3D CT volume?

And one more, my result with Ellipse shows only white screen
<img width="625" alt="image" src="https://github.com/user-attachments/assets/fc023162-27d4-4229-b1d8-6e5e5367e188">

Since the rendered image and initialization has been successfully done, I guessed that that's due to overlap of tremendous gaussians.
Is it proper result compare to previous your experiments?
Thanks a lot in advance for your reply!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Our X-Gaussian is mainly proposed for Novel View Synthesis. How to directly retrieve the CT volume is a difficult problem. For the CT reconstruction task. We firstly use X-Gaussian to generate projections. Then the synthesized and real projections are fed into traditional CT reconstruction methods to boost their performance.

If you want to directly reconstruct the CT volume, please follow our CVPR 2024 work - SAX-NeRF:
https://github.com/caiyuanhao1998/SAX-NeRF/

If you find our repo useful, please help us star it. Thanks :)

**Comment by byungjur96** [comment]
Then I'm wondering how did the Sparse-view CT reconstruction has been done
Is it right that the SVCT reconstruction experiments has been done with 5 given images and 95 synthesized novel view images?
Are these synthesized images are created only with 5 given images?

**Comment by caiyuanhao1998** [comment]
Yeah. Directly retrieving the 3D CT volume from the Gaussian point clouds is a very complicated problem. 

We have another paper to solve this problem. Please take a look at:

https://arxiv.org/abs/2405.20693

**Comment by byungjur96** [comment]
Thanks for guidance! Since your wonderful research SAX-NeRF, I've been keep following your researchs and inspired a lot from them.
I will check for the paper you've recommanded.
Thanks a lot again.

**Comment by caiyuanhao1998** [comment]
Thanks for your recognition!

If you find our repo useful, please help us star it. Thanks :)

**Comment by ecrinyagiz** [comment]
Hi, 

Thanks for the work and discussion here! Could you elaborate on the 3D volume from the Gaussian point cloud? My naive thoughts were at least you could render an arbitrary slice at a time with an assumed slice thickness. 

In the work shared above, integration bias is mentioned. To see this indeed happening, did you somehow do a volumetric representation out of the Gaussian point cloud and compare it with the ground truth? And is the bias happening because of the affine assumption in the transformation? (I am curious if this is a problem for other imaging scenarios)

Thanks in advance.
